### ISSUE TITLE
주문/결제 페이지

### ISSUE THREAD

**Issue by RubiYH** [Nior-Near/FE#4]
## ✔️TO-DO
UI 구현
- [x] 픽업장소, 주문자 정보 등 입력 후 '결제하기' 버튼
- [x] 주문 완료 페이지 **(UI 확정 안된듯)**
- [x] 주문 내역 페이지

기능 구현
