### ISSUE TITLE
요리사 신청하기 페이지

### ISSUE THREAD

**Issue by jisooooooooooo** [Nior-Near/FE#7]
## ✏️설명
요리사 신청하기 페이지

## ✔️TO-DO
- [x] 요리사 정보 페이지
- [ ] 메뉴 등록 페이지 
- [ ] 주문 정보 페이지 (개인 요리사, 니어 요리사 ver)
- [ ] 편지 등록 페이지
